#!/usr/bin/env python

from gradelib import *

r = Runner(save('jos.out'),
           stop_breakpoint('readline'))

@test(0, 'running JOS')
def test_jos():
    r.run_qemu()

@test(10)
def test_yield():
    r.user_test('yield')
    r.match('.PID     .. Hello!',
            '.PID     .. I am back! This is round 1',
            '.PID     .. I am back! This is round 2',
            '.PID     .. I am back! This is round 3',
            '.PID     .. I am back! This is round 4',
            '.PID     .. I am back! This is round 5',
            '.PID     .. I am done! Good bye!',
            '.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_waitnone():
    r.user_test('waitnone')
    r.match('.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_waitself():
    r.user_test('waitself')
    r.match('.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_basicfork():
    r.user_test('basicfork')
    r.match('.PID     .. New task with PID 2',
            '.PID     .. I am the child!',
            '.PID     .. I am the parent!',
            '.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 2',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_cowfork():
    r.user_test('cowfork')
    r.match('.PID     .. New task with PID 2',
            '.PID     .. I am the child!',
            '.PID     .. I am the parent!',
            '.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 2',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_reaper():
    r.user_test('reaper')
    r.match('.PID     .. New task with PID 2',
            '.PID     .. I am the child!',
            '.PID     .. I am the parent!',
            '.PID     .. Freed task with PID 2',
            '.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_wait():
    r.user_test('wait')
    r.match('.PID     .. New task with PID 2',
            '.PID     .. I am the child!',
            '.PID     .. Back again!',
            '.PID     .. Back again!',
            '.PID     .. Back again!',
            '.PID     .. Back again!',
            '.PID     .. Back again!',
            '.PID     .. Freed task with PID 2',
            '.PID     .. I am the parent!',
            '.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_evilchild():
    r.user_test('evilchild')
    r.match('.PID     .. New task with PID 2',
            '.PID     .. I am the child!',
            '.PID     .. Reaping task with PID 2',
            '.PID     .. Freed task with PID 1',
            '.PID     .. I am the parent!',
            '.PID     .. Exiting gracefully',
            '.PID     .. Freed task with PID 1',
            'Destroyed the only task - nothing more to do!')

@test(10)
def test_mcorefork():
    r.user_test('mcorefork')
    r.match('.PID ...... Running on CPU 0')
    r.match('.PID ...... Running on CPU 1')

@test(10)
def test_mempress():
    r.user_test('mempress')
    r.match('mempress successful.')

run_tests()

